name: pypsa-fixed-versions
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - coincbc
  - ipopt
  - snakemake=5.4.0
  - snakemake-minimal=5.4.0
  - affine=2.2.1
  - aioeasywebdav=2.2.0
  - aiohttp=3.4.2
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - async-timeout=3.0.0
  - attrs=18.2.0
  - backcall=0.1.0
  - basemap=1.2.0
  - basemap-data-hires=1.2.0
  - blas=1.1
  - blosc=1.14.4
  - bokeh=0.13.0
  - boost-cpp=1.67.0
  - boto3=1.8.5
  - botocore=1.11.6
  - bottleneck=1.2.1
  - bzip2=1.0.6
  - ca-certificates=2018.11.29
  - cachetools=2.1.0
  - cairo=1.14.12
  - certifi=2018.11.29
  - cffi=1.11.5
  - cftime=1.0.1
  - chardet=3.0.4
  - click=6.7
  - click-plugins=1.0.3
  - cligj=0.5.0
  - cloudpickle=0.5.5
  - conda-wrappers=1.0.3
  - configargparse=0.13.0
  - cryptography=2.3.1
  - cryptography-vectors=2.3.1
  - curl=7.61.0
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=0.19.0
  - dask-core=0.19.0
  - dbus=1.13.0
  - decorator=4.3.0
  - descartes=1.1.0
  - distributed=1.23.0
  - docutils=0.14
  - dropbox=9.0.0
  - exec-wrappers=1.1.1
  - expat=2.2.5
  - filechunkio=1.8
  - fiona=1.8.4
  - fontconfig=2.13.0
  - freetype=2.9.1
  - freexl=1.0.5
  - ftputil=3.4
  - gdal=2.3.2
  - geopandas=0.4.0
  - geos=3.6.2
  - geotiff=1.4.2
  - gettext=0.19.8.1
  - giflib=5.1.4
  - gitdb2=2.0.5
  - gitpython=2.1.11
  - glib=2.55.0
  - google-auth=1.5.1
  - google-auth-httplib2=0.0.2
  - google-cloud-core=0.24.1
  - google-cloud-storage=1.1.1
  - google-resumable-media=0.0.2
  - googleapis-common-protos=1.5.3
  - graphite2=1.3.12
  - graphviz=2.38.0
  - gst-plugins-base=1.12.5
  - gstreamer=1.12.5
  - h5netcdf=0.6.2
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf4=4.2.13
  - hdf5=1.10.3
  - heapdict=1.0.0
  - httplib2=0.11.3
  - icu=58.2
  - idna=2.7
  - idna_ssl=1.0.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - jedi=0.12.1
  - jinja2=2.10
  - jmespath=0.9.3
  - jpeg=9c
  - json-c=0.12.1
  - jsonschema=2.6.0
  - kealib=1.4.10
  - kiwisolver=1.0.1
  - krb5=1.14.6
  - libdap4=3.19.1
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libgdal=2.3.2
  - libgfortran=3.0.0
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.35
  - libpq=9.6.3
  - libprotobuf=3.6.0
  - libspatialindex=1.8.5
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libstdcxx-ng=7.2.0
  - libtiff=4.0.9
  - libtool=2.4.6
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - locket=0.2.0
  - lzo=2.10
  - markupsafe=1.0
  - matplotlib=3.0.2
  - matplotlib-base=3.0.2
  - memory_profiler=0.55.0
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - msgpack-python=0.5.6
  - multidict=4.3.1
  - munch=2.3.2
  - ncurses=6.1
  - netcdf4=1.4.2
  - networkx=2.2
  - nose=1.3.7
  - numexpr=2.6.6
  - numpy=1.15.4
  - openblas=0.3.3
  - openjpeg=2.3.0
  - openssl=1.0.2p
  - packaging=17.1
  - pandas=0.23.4
  - pango=1.40.14
  - paramiko=2.4.1
  - parso=0.3.1
  - partd=0.3.8
  - patsy=0.5.0
  - pcre=8.41
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pip=18.1
  - pixman=0.34.0
  - ply=3.11
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=9.6.3
  - prettytable=0.7.2
  - proj4=4.9.3
  - prompt_toolkit=2.0.7
  - protobuf=3.6.0
  - psutil=5.4.7
  - psycopg2=2.7.5
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.1
  - pycountry=18.12.8
  - pycparser=2.18
  - pygments=2.2.0
  - pygraphviz=1.4rc1
  - pynacl=1.1.2
  - pyomo=5.5.1
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyproj=1.9.5.1
  - pyqt=5.6.0
  - pysal=1.14.4.post2
  - pysftp=0.2.9
  - pyshp=2.0.0
  - pysocks=1.6.8
  - pytables=3.4.4
  - python=3.6.7
  - python-dateutil=2.7.3
  - python-irodsclient=0.7.0
  - pytz=2018.5
  - pyutilib=5.6.3
  - pyyaml=3.13
  - qt=5.6.2
  - rasterio=1.0.13
  - rasterstats=0.13.0
  - ratelimiter=1.2.0
  - readline=7.0
  - requests=2.19.1
  - rsa=3.4.2
  - rtree=0.8.3
  - s3transfer=0.1.13
  - scikit-learn=0.20.2
  - scipy=1.2.0
  - seaborn=0.9.0
  - setuptools=40.2.0
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - simplejson=3.16.0
  - sip=4.18.1
  - six=1.12.0
  - smmap2=2.0.5
  - snuggs=1.4.1
  - sortedcontainers=2.0.4
  - sqlalchemy=1.2.11
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - tblib=1.3.2
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=5.1
  - traitlets=4.3.2
  - urllib3=1.23
  - wcwidth=0.1.7
  - wheel=0.31.1
  - wrapt=1.10.11
  - xarray=0.11.0
  - xerces-c=3.2.0
  - xlrd=1.2.0
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.2
  - xorg-libx11=1.6.6
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xorg-libxext=1.3.3
  - xorg-libxpm=3.5.12
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - yarl=1.2.6
  - zict=0.1.3
  - zlib=1.2.11
  - bcrypt=3.1.4
  - datrie=0.7.1
  - intel-openmp=2018.0.3
  - libgfortran-ng=7.3.0
  - libopenblas=0.2.20
  - mkl=2018.0.3
  - numpy-base=1.14.3
  - pip:
    - pypsa>=0.13.2
    - vresutils>=0.3
    - git+https://github.com/FRESNA/atlite.git#egg
    - git+https://github.com/PyPSA/glaes.git#egg
    - git+https://github.com/PyPSA/geokit.git#egg

